wandb_version: 1

hidden_channels:
  desc: null
  value:
  - 128
  - 64
  - 32
epochs:
  desc: null
  value: 10
classes:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.0001
dataset:
  desc: null
  value: X.pkl, y.pkl (embedded peptide seq from classification
dropout_p:
  desc: null
  value: 0.2
architecture:
  desc: null
  value: CNN
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721561557.567472
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 1
      - 5
